version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: team_db
      POSTGRES_USER: team_user
      POSTGRES_PASSWORD: team_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - team-net

  backend:
    build: ./backend
    command: bash entrypoint.sh
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - team-net

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - team-net

volumes:
  postgres_data:

networks:
  team-net:
